// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1bUt7K8Dq2PVbA96IZHLmVkhxatGJiKo',
    appId: '1:829057867315:web:4a08df305e0230b60ecd46',
    messagingSenderId: '829057867315',
    projectId: 'task-cpf-fc3af',
    authDomain: 'task-cpf-fc3af.firebaseapp.com',
    storageBucket: 'task-cpf-fc3af.firebasestorage.app',
    measurementId: 'G-9N7X163HGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoQIQpTJnNTcoKPjSdDvNyiMS0MYf2q6M',
    appId: '1:829057867315:android:f672a1057537c8d00ecd46',
    messagingSenderId: '829057867315',
    projectId: 'task-cpf-fc3af',
    storageBucket: 'task-cpf-fc3af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRyks5SBHYaaZwIctVfSYeVOjIkBYdpNM',
    appId: '1:829057867315:ios:ae3d328a546022280ecd46',
    messagingSenderId: '829057867315',
    projectId: 'task-cpf-fc3af',
    storageBucket: 'task-cpf-fc3af.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRyks5SBHYaaZwIctVfSYeVOjIkBYdpNM',
    appId: '1:829057867315:ios:ae3d328a546022280ecd46',
    messagingSenderId: '829057867315',
    projectId: 'task-cpf-fc3af',
    storageBucket: 'task-cpf-fc3af.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1bUt7K8Dq2PVbA96IZHLmVkhxatGJiKo',
    appId: '1:829057867315:web:ace998bfa97239ce0ecd46',
    messagingSenderId: '829057867315',
    projectId: 'task-cpf-fc3af',
    authDomain: 'task-cpf-fc3af.firebaseapp.com',
    storageBucket: 'task-cpf-fc3af.firebasestorage.app',
    measurementId: 'G-7LXM7K6RSE',
  );

}